---
# tasks file for app
- name: Install Java From Apt-Get
  become: yes
  apt:
    name: openjdk-8-jdk
    state: latest

- name: Install Java From Apt-Get
  become: yes
  apt:
    name: openjdk-8-jre
    state: latest

- name: Create directory for java deplyment
  become: yes
  file:
    path: /root/app
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy file with owner and permissions
  become: yes
  copy:
    src: "{{ item }}"
    dest: /root/app/
    owner: root
    group: root
    mode: '0755'
  with_fileglob:
    - "/home/halodoc/deploy/simple*"

- name: Copy systemd service file to server
  become: yes
  copy:
    src: haloapp.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: '0755
  notify:
    - Start haloapp
