---
- name: Ensure group "nginx" exists
  group:
    name: nginx
    state: present
  
- name: Add the user nginx
  user:
    name: nginx
    shell: /bin/nologin
    groups: nginx

- name: Install NGINX From Apt-Get
  become: yes
  apt:
    name: nginx
    state: present

- name: Disable NGINX Default Virtual Host
  become: yes
  command:
    cmd: unlink /etc/nginx/sites-enabled/default

- name: Create NGINX Conf File For Application
  become: yes
  file:
    path: /etc/nginx/sites-available/app_proxy.conf
    owner: nginx
    group: nginx
    mode: 0644
    state: touch

- name: Amend NGINX Conf File
  become: yes
  blockinfile:
      path: /etc/nginx/sites-available/app_proxy.conf
      marker: ""
      block: |
        server {
            listen 80;
            location / {
                proxy_pass http://10.14.71.236:4000;
                proxy_set_header Authorization "";
                proxy_read_timeout 90s;
            }
	   location /admin {
                proxy_pass http://10.14.71.236:4001;
                proxy_set_header Authorization "";
                proxy_read_timeout 90s;
            }
        }

- name: Link NGINX Application Reverse Proxy
  become: yes
  command:
    cmd: ln -s /etc/nginx/sites-available/app_proxy.conf /etc/nginx/sites-enabled/app_proxy.conf

- name: Make Sure NGINX Service Is Running
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes
